### ISSUE TITLE
Refactor the hint positioning to work with more cases

### ISSUE THREAD

**Issue by KennethSundqvist** [KennethSundqvist/key-jump-chrome-extension#52]
Collect a lot of wonky edge cases before doing this.

Cases (so far):

* _Visible_ element with a single non-wrapping text node. (Single client rect.)
  * Position: The element or the client rect. Don't know if there is any practical difference.
* _Visible_ element with a single text node that wraps to multiple lines. (One client rect for each line.)
  * Position: First _visible_ client rect. (Some lines could be scrolled out of view and the lines can have different indentation or wrap around a shape.)
* _Collapsed_ element with only non-text child nodes.
  * Example: User picture besides a comment on a Github issue. https://github.com/EvilOatmeal/key-jump-chrome-extension/issues/52

**Comment by nskmda** [comment]
Not sure if this is in the works or something.
I noticed that if there are more than 10 elements on the page, it's impossible to select the first hint.
E.g, if there are 55 elements, I can't jump to 2, because there are 20, 21, 22 etc.
Or is there a way to activate the first hint matching?

**Comment by KennethSundqvist** [comment]
Hi @nskmda!

You can press `Enter` to activate the hint for the number you've typed. So you would press `2` > `Enter` to do that.

Thanks for letting me know that this behavior was unclear. I've updated the README to explain how this works.
